# Generated by Django 4.2.11 on 2024-09-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_memberships', '0031_alter_corpmembership_creator_and_more'),
        ('corporate_memberships', '0031_notice_region_notice_regions_to_exclude_and_more'),
    ]

    operations = [
    ]
