# Generated by Django 4.2.11 on 2024-08-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180315_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_category', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='categoryitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_parent', to='categories.category'),
        ),
    ]
