# Generated by Django 4.2.11 on 2024-09-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_add_groups_through_table'),
        ('events', '0036_alter_event_creator_alter_event_entity_and_more'),
    ]

    operations = [
    ]
