# Generated by Django 4.2.11 on 2024-09-08 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_merge_20240901_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_relations', to='events.event'),
        ),
    ]
