# Generated by Django 4.2.11 on 2024-08-18 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directories', '0024_auto_20210808_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='creator',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directory',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='directorypricing',
            name='duration',
            field=models.IntegerField(blank=True, choices=[(0, 'Unlimited'), (14, '14 Days from Activation date'), (30, '30 Days from Activation date'), (60, '60 Days from Activation date'), (90, '90 Days from Activation date'), (120, '120 Days from Activation date'), (365, '1 Year from Activation date'), (1826, '5 Years from Activation date')]),
        ),
    ]
